version: '3.9'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_example
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_ROOT_PASSWORD: ThePassword